### ISSUE TITLE
How to get access to the API?

### ISSUE THREAD

**Issue by jastax** [TrainingPeaks/tp-public-api-auth#2]
According to the TP website (https://api.trainingpeaks.com/request-access) you are currently not granting API access to new applications. Is it possible again? How can we get access to the API?

Thanks and all the best
Jan

**Comment by jeremyduerksen** [comment]
Thank you for the question @jastax. As noted, we are not granting access for new applicants at this time. There is no ETA to re-open access. If you would like, please go ahead and fill out the request form, and when we do re-open our evaluation process we'll have your request on file to review. Thank you for your interest in our API.
